# Generated by Django 3.2 on 2022-10-05 10:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_category', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('drinks', 'drinks'), ('desserts', 'desserts')], max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='menu_photo', validators=[django.core.validators.FileExtensionValidator(['png'])], verbose_name='menu photo')),
                ('price', models.FloatField()),
                ('availability', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('guests', models.IntegerField()),
                ('e_mail', models.EmailField(max_length=254)),
                ('booking_number', models.CharField(max_length=100)),
                ('date_visiting', models.DateField()),
                ('time_visiting', models.TimeField()),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booking_time', models.TimeField(auto_now_add=django.utils.timezone.localtime)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=150)),
                ('order_number', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_time', models.TimeField(auto_now_add=django.utils.timezone.localtime)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('e_mail', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=500)),
                ('date_sent', models.DateField(auto_now_add=True)),
                ('time_sent', models.TimeField(auto_now_add=django.utils.timezone.localtime)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
