# Generated by Django 3.2 on 2022-10-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('shipping', 'shipping'), ('delivered', 'delivered')], max_length=20),
        ),
    ]
