# Generated by Django 3.2 on 2022-10-06 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='photo',
            field=models.ImageField(upload_to='menu_photo', validators=[django.core.validators.FileExtensionValidator(['png'], ['jpg'])], verbose_name='menu photo'),
        ),
    ]
